services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: "aacosdev123"
      POSTGRES_USER: aacos
      POSTGRES_DB: aacos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  qdrant_data:
  db_data:
