services:
  frontend:
    build: ./frontend
    container_name: aacos_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: always
    depends_on:
      - backend
    networks:
      - aacosnet

  backend:
    build: ./backend
    container_name: aacos_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - postgres
      - qdrant
    networks:
      - aacosnet

  qdrant:
    image: qdrant/qdrant
    container_name: aacos_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    networks:
      - aacosnet

  postgres:
    image: postgres:15
    container_name: aacos_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aacos
      - POSTGRES_USER=aacos
      - POSTGRES_PASSWORD=aacosdev123
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - aacosnet

volumes:
  qdrant_data:
  pg_data:

networks:
  aacosnet:
